[Transient Velocity Tests]
    paths = plotters\version2\A2356raw2.dat, b.dat, c.dat
    measure = ET, 4  # increasing from 4 decreases extracted data points
    #  archiving creates, graphing option, just going to create PNG line and SVG scatter
    creates = a.png, b.png, c.png #or creates = SUBPLOTS
    graphing=line #or graphing=scatter, 0.001
    axis = ET, V
    xTicks = 0, 1100, 200
    yTicks = -5, 35, 5
[Transient Normal Load Tests]
    ...
[Transient Inclination Angle Tests]
    ...
[Transient Slip Angle Tests]
    ...
[Transient Slip Ratio Tests (SL)]
    ...
[Transient Slip Ratio Tests (SR)]
    ...
[Transient Tire Pressure Tests]
    ...
